pipeline {
    agent any
    environment {
        MAVEN_HOME = tool 'Default Maven'
        SONAR_PROJECT_KEY = 'GestionBiblio'
        SONAR_SCANNER_HOME = tool 'SonarQubeScanner'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/imraneahm/GestionBibliotheque.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                echo 'Building project...'
                sh "${MAVEN_HOME}/bin/mvn clean compile"
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh "${MAVEN_HOME}/bin/mvn test"
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${MAVEN_HOME}/bin/mvn clean verify sonar:sonar \
                          -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                          -Dsonar.projectName='GestionBiblio' \
                          -Dsonar.host.url=http://localhost:9000 \
                          -Dsonar.token=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment simulation successful!'
            }
        }
    }

    post {
        success {
            mail to: 'imraneaithammou1@gmail.com',
                subject: "Pipeline réussie: ${currentBuild.fullDisplayName}",
                body: """
                    Le build a été complété avec succès.
                    Build URL: ${BUILD_URL}
                    Détails du build :
                    - Branche: main
                    - Commit: ${GIT_COMMIT}
                    - Build number: ${BUILD_NUMBER}
                    """
        }
        failure {
            mail to: 'imraneaithammou1@gmail.com',
                subject: "Pipeline échouée: ${currentBuild.fullDisplayName}",
                body: """
                    Le build a échoué.
                    Build URL: ${BUILD_URL}
                    Détails du build :
                    - Branche: main
                    - Commit: ${GIT_COMMIT}
                    - Build number: ${BUILD_NUMBER}
                    Veuillez vérifier les logs pour plus de détails.
                    """
        }
        always {
            cleanWs()
        }
    }
}
